server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbmovie
    username: root
    password: 3871
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      '[hibernate.format_sql]': true
